pipeline {
    agent any

    stages{
        stage("Install"){
            steps{
                echo "Instalando dependências"
                dir("pipeline-jenkins-nodejs") {
                    bat "npm install"
                }
            }
        }
        stage("Build") {
            steps {
                dir("pipeline-jenkins-nodejs") {
                    bat "npm run build"
                }
            }
        }
        stage("Test") {
            steps {
                dir("pipeline-jenkins-nodejs") {
                    bat "npm test"
                }
            }
        }
    }
    post { 
        success { 
            echo 'Sucesso'
        }
        failure { 
            echo 'Falha'
        }
    }
}